name: notestash
description: "An app that helps you in organising your thoughts."

publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: ">=3.6.0 <4.0.0" # ✅ good range for null safety and Dart 3

dependencies:
  flutter:
    sdk: flutter

  table_calendar: ^3.0.9
  english_words: ^4.0.0
  provider: ^6.1.2
  google_fonts: ^6.1.0
  intl: ^0.18.1
  timezone: ^0.9.2 # ✅ moved to the correct place

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true