name: notestash
description: "An app that helps you in organising your thoughts."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  table_calendar: ^3.0.9
  english_words: ^4.0.0
  provider: ^6.1.2
  google_fonts: ^6.1.0
  intl: ^0.18.1
  flutter_local_notifications: ^19.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
